{
 "title": "KubeDB / Solr / Database",
 "tags": [
  "kubedb",
  "solr"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "zk_host",
    "query": {
     "query": "label_values(solr_ping{zk_host=~\".+\"},zk_host)"
    }
   },
   {
    "name": "base_url",
    "query": {
     "query": "label_values(solr_ping{base_url=~\".+\"},base_url)"
    }
   },
   {
    "name": "collection",
    "query": {
     "query": "label_values(solr_collections_shard_state{zk_host=~\"$zk_host\",collection=~\".+\"},collection)"
    }
   },
   {
    "name": "shard",
    "query": {
     "query": "label_values(solr_collections_shard_state{zk_host=~\"$zk_host\",collection=~\"$collection\",shard=~\".+\"},shard)"
    }
   },
   {
    "name": "replica",
    "query": {
     "query": "label_values(solr_collections_replica_state{zk_host=~\"$zk_host\",collection=~\"$collection\",shard=~\"$shard\",replica=~\".+\"},replica)"
    }
   },
   {
    "name": "core",
    "query": {
     "query": "label_values(solr_collections_replica_state{zk_host=~\"$zk_host\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\"},core)"
    }
   },
   {
    "name": "searchHandler",
    "query": {
     "query": "label_values(solr_metrics_core_query_errors_1minRate{collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\"},searchHandler)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(solr_ping{job=~\".+\",namespace=~\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Solr Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of live nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (zk_host) (solr_collections_live_nodes{namespace=\"$namespace\",job=\"$job\"})",
       "legendFormat": "Live nodes"
      },
      {
       "expr": "max by (core) (count(count by (node_name) (solr_collections_replica_state{namespace=\"$namespace\",job=\"$job\"})) < solr_collections_live_nodes{namespace=\"$namespace\",job=\"$job\"} or solr_collections_live_nodes{namespace=\"$namespace\",job=\"$job\"})",
       "legendFormat": "Total nodes"
      }
     ]
    },
    {
     "title": "Shard leaders",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Leaders" }
     ],
     "targets": [
      {
       "expr": "max by (core,replica, shard, collection) (solr_collections_shard_leader{namespace=\"$namespace\",job=\"$job\"})",
       "legendFormat": "{{core}}"
      }
     ]
    },
    {
     "title": "Number of collections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by (collection)  (solr_collections_replica_state{namespace=\"$namespace\",job=\"$job\"}))"
      }
     ]
    },
    {
     "title": "Current replica state",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(max by (core) (solr_collections_replica_state{namespace=\"$namespace\",job=\"$job\"}))",
       "legendFormat": "Total replicas"
      },
      {
       "expr": "count(max by (core) (solr_collections_replica_state{namespace=\"$namespace\",job=\"$job\",state=\"active\"})) OR on() vector(0)",
       "legendFormat": "Active"
      },
      {
       "expr": "count(max by (core) (solr_collections_replica_state{namespace=\"$namespace\",job=\"$job\",state=\"down\"})) OR on() vector(0)",
       "legendFormat": "Down"
      },
      {
       "expr": "count(max by (core) (solr_collections_replica_state{namespace=\"$namespace\",job=\"$job\",state=\"recovering\"})) OR on() vector(0)",
       "legendFormat": "Recovering"
      },
      {
       "expr": "count(max by (core) (solr_collections_replica_state{namespace=\"$namespace\",job=\"$job\",state=\"recovery_failed\"})) OR on() vector(0)",
       "legendFormat": "Recovery failed"
      }
     ]
    },
    {
     "title": "Zookeepers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(count(max by (host) (solr_zookeeper_nodestatus{namespace=\"$namespace\",job=\"$job\"}) == 1))",
       "legendFormat": "Healthy nodes"
      },
      {
       "expr": "max by (zk_host) (solr_zookeeper_ensemble_size{namespace=\"$namespace\",job=\"$job\"})",
       "legendFormat": "Ensemble size"
      }
     ]
    },
    {
     "title": "Replica state history",
     "type": "graph",
     "description": "Active replicas have value 0. Non-active replicas will show stacked in the graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "Non-active states" }
     ],
     "targets": [
      {
       "expr": "1 - max by (core, state) (solr_collections_replica_state{namespace=\"$namespace\",job=\"$job\"})",
       "legendFormat": "{{core}} = {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total QPS (by collection)",
     "type": "graph",
     "description": "Distributed QPS 1-min rate  aggregated by collection, roughly the current QPS across all nodes per collection",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "qps" }
     ],
     "targets": [
      {
       "expr": "sum by (collection) (solr_metrics_core_query_1minRate{namespace=\"$namespace\",job=\"$job\"})",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Total QPS (by node)",
     "type": "graph",
     "description": "Distributed QPS 1-min rate aggregated by base_url (Solr node)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (base_url) (solr_metrics_core_query_1minRate{namespace=\"$namespace\",job=\"$job\"})",
       "legendFormat": "{{base_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_buffers{namespace=\"$namespace\",job=\"$job\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{pool}}"
      }
     ]
    },
    {
     "title": "Buffer Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_buffers_bytes{namespace=\"$namespace\",job=\"$job\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{pool}} {{item}}"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_jvm_gc_total{namespace=\"$namespace\",job=\"$job\",base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "GC Time Seconds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_jvm_gc_seconds_total{base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Heap Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_heap_bytes{namespace=\"$namespace\",job=\"$job\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Non-Heap Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_non_heap_bytes{namespace=\"$namespace\",job=\"$job\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Pool Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_pools_bytes{namespace=\"$namespace\",job=\"$job\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{space}} {{item}}"
      }
     ]
    },
    {
     "title": "Memory Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_bytes{namespace=\"$namespace\",job=\"$job\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_threads{namespace=\"$namespace\",job=\"$job\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true
  }
 ]
}